#!/usr/bin/env bash
# sync_ipynbs.sh
# Converts every .ipynb in the repo to a .py file for easy GitHub browsing.
# Markdown cells → triple-quoted string blocks (''' ... ''')
# Code cells     → raw Python with # %% separators
# Run from anywhere; auto-detects repo root from script location.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "$0")" && pwd)"

# Write converter to a temp file so the while-loop stdin stays clean
CONVERTER=$(mktemp /tmp/nb2py_XXXXXX.py)
trap "rm -f $CONVERTER" EXIT

cat > "$CONVERTER" << 'PYEOF'
import json, sys, os, textwrap

nb_path = sys.argv[1]
py_path = sys.argv[2]
nb_name = os.path.basename(nb_path)

with open(nb_path, encoding='utf-8') as f:
    nb = json.load(f)

out = []
out.append('# -*- coding: utf-8 -*-')
out.append(f'# {nb_name}  (auto-generated by sync_ipynbs.sh — edit the notebook, not this file)')
out.append('')

for cell in nb['cells']:
    src = ''.join(cell['source']).strip()
    if not src:
        continue

    if cell['cell_type'] == 'markdown':
        out.append('# %% [markdown]')
        # Escape any triple-single-quotes inside the markdown so the block stays valid
        safe = src.replace("'''", '"""')
        out.append("'''")
        out.append(safe)
        out.append("'''")
        out.append('')

    elif cell['cell_type'] == 'code':
        out.append('# %%')
        out.append(src)
        out.append('')

with open(py_path, 'w', encoding='utf-8') as f:
    f.write('\n'.join(out) + '\n')

print(f'  {os.path.relpath(nb_path)} -> {os.path.relpath(py_path)}')
PYEOF

echo "Syncing notebooks → .py files"
echo "Repo: $REPO_ROOT"
echo ""

find "$REPO_ROOT" \
    -name "*.ipynb" \
    -not -path "*/.ipynb_checkpoints/*" \
    -not -path "*/.git/*" \
    -not -path "*/node_modules/*" \
    | sort | while read -r nb; do
    py="${nb%.ipynb}.py"
    python3 "$CONVERTER" "$nb" "$py"
done

echo ""
echo "Done."
